In [1]:
from StarKiller.initialization import starkiller_initialize
from StarKiller.interfaces import BurnType
from StarKiller.integration import Integrator
from StarKiller.network import Network
import numpy as np

In [2]:
probin_file = "probin_aprox21"

In [3]:
starkiller_initialize(probin_file)


Initialized StarKiller with ...
- EOS:     helmholtz
- Network: aprox21


In [4]:
integrator = Integrator()
network = Network()

In [5]:
state_in = BurnType()

In [6]:
state_in.state.rho = 1.0e9
state_in.state.t = 1.0e9
state_in.state.xn = np.zeros(21)
state_in.state.xn[network.species_map["he4"]] = 1.0

In [7]:
print(state_in.ydot)
print(state_in.jac)
print(state_in.state)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

In [8]:
dt = 1.0e-9

In [9]:
out_state = integrator.integrate(state_in, dt)
network.rhs(out_state)
network.jacobian(out_state)

In [10]:
print(out_state.ydot)
print(out_state.jac)
print(out_state.state)

[-4.50075282e-20  1.42153135e-30 -9.20017306e+06  3.06586120e+06
  2.22847710e-20  6.17135922e+02  2.17373131e+01  1.98621144e+00
  4.36800840e-02  2.30058705e-05  4.47631748e-09  1.72756887e-13
  2.59980404e-19  2.79235781e-26  4.34951765e-36  1.57620893e-29
  1.51181407e-30  5.83466831e-31 -4.14905692e-32  1.72019802e-30
  3.46333413e-30  4.54978549e+17  2.15288364e+25]
[[-4.50075282e+10 -8.96000000e-01  0.00000000e+00 -1.12978697e-17
  -9.30574320e-19 -1.48797101e-19  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00 -2.20647381e-29  0.00000000e+00]
 [ 1.72019802e+00 -8.96000000e-01  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e